

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${DB_NAME:coupon}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maxLifetime: 580000
      maximum-pool-size: 10
    password: ${MYSQL_PASSWORD:0012}
    username: ${MYSQL_USERNAME:root}
  jpa:
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
        default_batch_fetch_size: ${JPA_BATCH_FETCH_SIZE:100}
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  sql:
    init:
      mode: always
